spring:
  application:
    name: config-server
  profiles:
    active:
    - native, vault
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        vault:
          host: 192.168.1.102
          port: 8200
          kvVersion: 2
    
server:
  port: 8071
  
#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"